name: Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:     
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        