name: Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        